import { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Vercel",
    description:
      "We're looking for a senior frontend engineer to work on Next.js tooling and our dashboard product. You'll own features end-to-end, collaborate with a small team, and ship to a large developer audience.",
    location: "San Francisco, CA",
    workArrangement: "remote",
    employmentType: "full-time",
    companySize: "medium",
    industry: "Technology",
    skills: ["React", "TypeScript", "Next.js", "CSS", "Node.js"],
    salaryRange: "$180k – $250k",
    applyUrl: "#",
    matchScore: 95,
    matchReason:
      "Strong overlap with your React and TypeScript skills. Remote role matches your work arrangement preference.",
    postedDate: "2026-03-01",
  },
  {
    id: "2",
    title: "Game Systems Designer",
    company: "Riot Games",
    description:
      "Join a new project team to design and balance core gameplay systems. You'll prototype mechanics, run playtests, and work closely with engineers to iterate on game feel.",
    location: "Los Angeles, CA",
    coordinates: { lat: 34.0522, lng: -118.2437 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "large",
    industry: "Gaming",
    skills: ["Game Design", "Systems Thinking", "Prototyping", "Data Analysis"],
    salaryRange: "$130k – $190k",
    applyUrl: "#",
    matchScore: 88,
    matchReason:
      "Your interest in gaming and systems design lines up well. Hybrid arrangement in LA.",
    postedDate: "2026-02-28",
  },
  {
    id: "3",
    title: "Product Designer",
    company: "Linear",
    description:
      "We need a product designer who obsesses over details and cares about developer tools. You'll own end-to-end design for core product areas and ship weekly with a tight engineering team.",
    location: "Remote",
    workArrangement: "remote",
    employmentType: "full-time",
    companySize: "startup",
    industry: "SaaS",
    skills: [
      "Figma",
      "UI/UX Design",
      "Design Systems",
      "Prototyping",
      "User Research",
    ],
    salaryRange: "$160k – $220k",
    applyUrl: "#",
    matchScore: 91,
    matchReason:
      "Matches your design skills and preference for small, product-focused teams.",
    postedDate: "2026-03-02",
  },
  {
    id: "4",
    title: "Machine Learning Engineer",
    company: "OpenAI",
    description:
      "Work on training and fine-tuning large language models. You'll experiment with architectures, debug training runs, and collaborate with researchers. Strong Python and PyTorch experience required.",
    location: "San Francisco, CA",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    workArrangement: "onsite",
    employmentType: "full-time",
    companySize: "medium",
    industry: "AI & Machine Learning",
    skills: [
      "Python",
      "PyTorch",
      "Machine Learning",
      "Mathematics",
      "Research",
    ],
    salaryRange: "$250k – $400k",
    applyUrl: "#",
    matchScore: 82,
    matchReason:
      "Your Python background is relevant. Onsite in SF — check if that fits your location preference.",
    postedDate: "2026-02-25",
  },
  {
    id: "5",
    title: "Full Stack Developer",
    company: "Stripe",
    description:
      "Build and maintain payment APIs and internal tools. You'll work across Ruby and React, tackle database performance, and help design APIs that thousands of businesses depend on.",
    location: "Seattle, WA",
    coordinates: { lat: 47.6062, lng: -122.3321 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "large",
    industry: "Fintech",
    skills: [
      "Ruby",
      "React",
      "PostgreSQL",
      "API Design",
      "Distributed Systems",
    ],
    salaryRange: "$190k – $280k",
    applyUrl: "#",
    matchScore: 86,
    matchReason:
      "Good fit for your full-stack experience. Fintech industry aligns with your finance interest.",
    postedDate: "2026-03-03",
  },
  {
    id: "6",
    title: "Technical Writer",
    company: "Notion",
    description:
      "Write and maintain developer docs, guides, and API references. You'll work with engineering teams to understand features and translate complex concepts into clear, concise documentation.",
    location: "New York, NY",
    workArrangement: "remote",
    employmentType: "full-time",
    companySize: "medium",
    industry: "SaaS",
    skills: [
      "Technical Writing",
      "Documentation",
      "Markdown",
      "API Documentation",
    ],
    salaryRange: "$120k – $170k",
    applyUrl: "#",
    matchScore: 79,
    matchReason:
      "Relevant if you have writing experience. Fully remote, which matches your preference.",
    postedDate: "2026-02-27",
  },
  {
    id: "7",
    title: "DevOps Engineer",
    company: "Datadog",
    description:
      "Manage and improve CI/CD pipelines, cloud infrastructure, and monitoring for a large-scale SaaS platform. Terraform, Kubernetes, and AWS experience expected.",
    location: "Boston, MA",
    coordinates: { lat: 42.3601, lng: -71.0589 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "large",
    industry: "Technology",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Python"],
    salaryRange: "$170k – $240k",
    applyUrl: "#",
    matchScore: 77,
    matchReason:
      "Partial skill overlap with your Python experience. Infrastructure focus may differ from your current track.",
    postedDate: "2026-03-01",
  },
  {
    id: "8",
    title: "UX Researcher",
    company: "Figma",
    description:
      "Plan and run user studies, usability tests, and surveys to inform product decisions. You'll partner with designers and PMs to identify research questions and turn findings into recommendations.",
    location: "San Francisco, CA",
    coordinates: { lat: 37.7849, lng: -122.4094 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "medium",
    industry: "Technology",
    skills: [
      "User Research",
      "Data Analysis",
      "Interviewing",
      "Usability Testing",
      "Figma",
    ],
    salaryRange: "$140k – $200k",
    applyUrl: "#",
    matchScore: 84,
    matchReason:
      "Fits well if you have research and analytical skills. Creative tools company aligns with design interest.",
    postedDate: "2026-02-26",
  },
  {
    id: "9",
    title: "Climate Data Scientist",
    company: "Watershed",
    description:
      "Analyze carbon emissions data and build models to help enterprise customers track and reduce their environmental footprint. SQL, Python, and data visualization skills needed.",
    location: "Remote",
    workArrangement: "remote",
    employmentType: "full-time",
    companySize: "startup",
    industry: "Climate Tech",
    skills: ["Python", "Data Science", "SQL", "Statistics", "Visualization"],
    salaryRange: "$150k – $210k",
    applyUrl: "#",
    matchScore: 80,
    matchReason:
      "Data and Python skills are a match. Remote role at a mission-driven startup.",
    postedDate: "2026-03-02",
  },
  {
    id: "10",
    title: "iOS Engineer",
    company: "Arc Browser",
    description:
      "Build and ship features for Arc's iOS app. Small team, so you'll own large surface areas — from networking to custom UI components. SwiftUI is our primary framework but UIKit knowledge helps.",
    location: "New York, NY",
    coordinates: { lat: 40.7128, lng: -74.006 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "startup",
    industry: "Technology",
    skills: ["Swift", "SwiftUI", "iOS Development", "UIKit", "Performance"],
    salaryRange: "$170k – $230k",
    applyUrl: "#",
    matchScore: 73,
    matchReason:
      "Relevant if you have mobile development experience. Small startup team in NYC.",
    postedDate: "2026-02-28",
  },
  {
    id: "11",
    title: "Backend Engineer",
    company: "Supabase",
    description:
      "Work on our open-source Postgres platform — auth, realtime, storage, and edge functions. You'll write Go and TypeScript, review community PRs, and help shape the roadmap. Async-first culture.",
    location: "Remote",
    workArrangement: "remote",
    employmentType: "full-time",
    companySize: "startup",
    industry: "Technology",
    skills: [
      "PostgreSQL",
      "Go",
      "TypeScript",
      "Distributed Systems",
      "Open Source",
    ],
    salaryRange: "$160k – $220k",
    applyUrl: "#",
    matchScore: 87,
    matchReason:
      "Backend and TypeScript skills are a strong match. Remote + open-source culture fits your preferences.",
    postedDate: "2026-03-01",
  },
  {
    id: "12",
    title: "Curriculum Designer",
    company: "Khan Academy",
    description:
      "Design math and science curricula for K-12 learners. You'll create lesson plans, assessments, and interactive exercises. Teaching or tutoring experience is a strong plus.",
    location: "Mountain View, CA",
    coordinates: { lat: 37.3861, lng: -122.0839 },
    workArrangement: "hybrid",
    employmentType: "full-time",
    companySize: "medium",
    industry: "Education",
    skills: [
      "Curriculum Design",
      "Educational Technology",
      "Content Strategy",
      "Assessment Design",
    ],
    salaryRange: "$110k – $160k",
    applyUrl: "#",
    matchScore: 76,
    matchReason:
      "Relevant if you're interested in education. Hybrid role in Mountain View.",
    postedDate: "2026-02-24",
  },
];
